/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ClientDetailsDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T13:18:11.102+01:00")
public class ClientDetailsDTO {
  @SerializedName("accessTokenValiditySeconds")
  private Long accessTokenValiditySeconds = null;

  @SerializedName("additionalInformation")
  private Map<String, String> additionalInformation = new HashMap<String, String>();

  @SerializedName("authorities")
  private List<String> authorities = new ArrayList<String>();

  @SerializedName("authorizedGrantTypes")
  private List<String> authorizedGrantTypes = new ArrayList<String>();

  @SerializedName("autoApproveScopes")
  private List<String> autoApproveScopes = new ArrayList<String>();

  @SerializedName("clientId")
  private String clientId = null;

  @SerializedName("clientSecret")
  private String clientSecret = null;

  @SerializedName("refreshTokenValiditySeconds")
  private Long refreshTokenValiditySeconds = null;

  @SerializedName("registeredRedirectUri")
  private List<String> registeredRedirectUri = new ArrayList<String>();

  @SerializedName("resourceIds")
  private List<String> resourceIds = new ArrayList<String>();

  @SerializedName("scope")
  private List<String> scope = new ArrayList<String>();

  public ClientDetailsDTO accessTokenValiditySeconds(Long accessTokenValiditySeconds) {
    this.accessTokenValiditySeconds = accessTokenValiditySeconds;
    return this;
  }

   /**
   * Get accessTokenValiditySeconds
   * @return accessTokenValiditySeconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAccessTokenValiditySeconds() {
    return accessTokenValiditySeconds;
  }

  public void setAccessTokenValiditySeconds(Long accessTokenValiditySeconds) {
    this.accessTokenValiditySeconds = accessTokenValiditySeconds;
  }

  public ClientDetailsDTO additionalInformation(Map<String, String> additionalInformation) {
    this.additionalInformation = additionalInformation;
    return this;
  }

  public ClientDetailsDTO putAdditionalInformationItem(String key, String additionalInformationItem) {
    this.additionalInformation.put(key, additionalInformationItem);
    return this;
  }

   /**
   * Get additionalInformation
   * @return additionalInformation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getAdditionalInformation() {
    return additionalInformation;
  }

  public void setAdditionalInformation(Map<String, String> additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  public ClientDetailsDTO authorities(List<String> authorities) {
    this.authorities = authorities;
    return this;
  }

  public ClientDetailsDTO addAuthoritiesItem(String authoritiesItem) {
    this.authorities.add(authoritiesItem);
    return this;
  }

   /**
   * Get authorities
   * @return authorities
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAuthorities() {
    return authorities;
  }

  public void setAuthorities(List<String> authorities) {
    this.authorities = authorities;
  }

  public ClientDetailsDTO authorizedGrantTypes(List<String> authorizedGrantTypes) {
    this.authorizedGrantTypes = authorizedGrantTypes;
    return this;
  }

  public ClientDetailsDTO addAuthorizedGrantTypesItem(String authorizedGrantTypesItem) {
    this.authorizedGrantTypes.add(authorizedGrantTypesItem);
    return this;
  }

   /**
   * Get authorizedGrantTypes
   * @return authorizedGrantTypes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAuthorizedGrantTypes() {
    return authorizedGrantTypes;
  }

  public void setAuthorizedGrantTypes(List<String> authorizedGrantTypes) {
    this.authorizedGrantTypes = authorizedGrantTypes;
  }

  public ClientDetailsDTO autoApproveScopes(List<String> autoApproveScopes) {
    this.autoApproveScopes = autoApproveScopes;
    return this;
  }

  public ClientDetailsDTO addAutoApproveScopesItem(String autoApproveScopesItem) {
    this.autoApproveScopes.add(autoApproveScopesItem);
    return this;
  }

   /**
   * Get autoApproveScopes
   * @return autoApproveScopes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAutoApproveScopes() {
    return autoApproveScopes;
  }

  public void setAutoApproveScopes(List<String> autoApproveScopes) {
    this.autoApproveScopes = autoApproveScopes;
  }

  public ClientDetailsDTO clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ClientDetailsDTO clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Get clientSecret
   * @return clientSecret
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public ClientDetailsDTO refreshTokenValiditySeconds(Long refreshTokenValiditySeconds) {
    this.refreshTokenValiditySeconds = refreshTokenValiditySeconds;
    return this;
  }

   /**
   * Get refreshTokenValiditySeconds
   * @return refreshTokenValiditySeconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getRefreshTokenValiditySeconds() {
    return refreshTokenValiditySeconds;
  }

  public void setRefreshTokenValiditySeconds(Long refreshTokenValiditySeconds) {
    this.refreshTokenValiditySeconds = refreshTokenValiditySeconds;
  }

  public ClientDetailsDTO registeredRedirectUri(List<String> registeredRedirectUri) {
    this.registeredRedirectUri = registeredRedirectUri;
    return this;
  }

  public ClientDetailsDTO addRegisteredRedirectUriItem(String registeredRedirectUriItem) {
    this.registeredRedirectUri.add(registeredRedirectUriItem);
    return this;
  }

   /**
   * Get registeredRedirectUri
   * @return registeredRedirectUri
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getRegisteredRedirectUri() {
    return registeredRedirectUri;
  }

  public void setRegisteredRedirectUri(List<String> registeredRedirectUri) {
    this.registeredRedirectUri = registeredRedirectUri;
  }

  public ClientDetailsDTO resourceIds(List<String> resourceIds) {
    this.resourceIds = resourceIds;
    return this;
  }

  public ClientDetailsDTO addResourceIdsItem(String resourceIdsItem) {
    this.resourceIds.add(resourceIdsItem);
    return this;
  }

   /**
   * Get resourceIds
   * @return resourceIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getResourceIds() {
    return resourceIds;
  }

  public void setResourceIds(List<String> resourceIds) {
    this.resourceIds = resourceIds;
  }

  public ClientDetailsDTO scope(List<String> scope) {
    this.scope = scope;
    return this;
  }

  public ClientDetailsDTO addScopeItem(String scopeItem) {
    this.scope.add(scopeItem);
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getScope() {
    return scope;
  }

  public void setScope(List<String> scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientDetailsDTO clientDetailsDTO = (ClientDetailsDTO) o;
    return Objects.equals(this.accessTokenValiditySeconds, clientDetailsDTO.accessTokenValiditySeconds) &&
        Objects.equals(this.additionalInformation, clientDetailsDTO.additionalInformation) &&
        Objects.equals(this.authorities, clientDetailsDTO.authorities) &&
        Objects.equals(this.authorizedGrantTypes, clientDetailsDTO.authorizedGrantTypes) &&
        Objects.equals(this.autoApproveScopes, clientDetailsDTO.autoApproveScopes) &&
        Objects.equals(this.clientId, clientDetailsDTO.clientId) &&
        Objects.equals(this.clientSecret, clientDetailsDTO.clientSecret) &&
        Objects.equals(this.refreshTokenValiditySeconds, clientDetailsDTO.refreshTokenValiditySeconds) &&
        Objects.equals(this.registeredRedirectUri, clientDetailsDTO.registeredRedirectUri) &&
        Objects.equals(this.resourceIds, clientDetailsDTO.resourceIds) &&
        Objects.equals(this.scope, clientDetailsDTO.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessTokenValiditySeconds, additionalInformation, authorities, authorizedGrantTypes, autoApproveScopes, clientId, clientSecret, refreshTokenValiditySeconds, registeredRedirectUri, resourceIds, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientDetailsDTO {\n");
    
    sb.append("    accessTokenValiditySeconds: ").append(toIndentedString(accessTokenValiditySeconds)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    authorities: ").append(toIndentedString(authorities)).append("\n");
    sb.append("    authorizedGrantTypes: ").append(toIndentedString(authorizedGrantTypes)).append("\n");
    sb.append("    autoApproveScopes: ").append(toIndentedString(autoApproveScopes)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    refreshTokenValiditySeconds: ").append(toIndentedString(refreshTokenValiditySeconds)).append("\n");
    sb.append("    registeredRedirectUri: ").append(toIndentedString(registeredRedirectUri)).append("\n");
    sb.append("    resourceIds: ").append(toIndentedString(resourceIds)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

