/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * MinimalSourceDetailsDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T13:18:11.102+01:00")
public class MinimalSourceDetailsDTO {
  @SerializedName("assigned")
  private Boolean assigned = null;

  @SerializedName("attributes")
  private Map<String, String> attributes = new HashMap<String, String>();

  @SerializedName("expectedSourceName")
  private String expectedSourceName = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("sourceId")
  private String sourceId = null;

  @SerializedName("sourceName")
  private String sourceName = null;

  @SerializedName("sourceTypeCatalogVersion")
  private String sourceTypeCatalogVersion = null;

  @SerializedName("sourceTypeId")
  private Long sourceTypeId = null;

  @SerializedName("sourceTypeModel")
  private String sourceTypeModel = null;

  @SerializedName("sourceTypeProducer")
  private String sourceTypeProducer = null;

  public MinimalSourceDetailsDTO assigned(Boolean assigned) {
    this.assigned = assigned;
    return this;
  }

   /**
   * Get assigned
   * @return assigned
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAssigned() {
    return assigned;
  }

  public void setAssigned(Boolean assigned) {
    this.assigned = assigned;
  }

  public MinimalSourceDetailsDTO attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public MinimalSourceDetailsDTO putAttributesItem(String key, String attributesItem) {
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public MinimalSourceDetailsDTO expectedSourceName(String expectedSourceName) {
    this.expectedSourceName = expectedSourceName;
    return this;
  }

   /**
   * Get expectedSourceName
   * @return expectedSourceName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExpectedSourceName() {
    return expectedSourceName;
  }

  public void setExpectedSourceName(String expectedSourceName) {
    this.expectedSourceName = expectedSourceName;
  }

  public MinimalSourceDetailsDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public MinimalSourceDetailsDTO sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public MinimalSourceDetailsDTO sourceName(String sourceName) {
    this.sourceName = sourceName;
    return this;
  }

   /**
   * Get sourceName
   * @return sourceName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceName() {
    return sourceName;
  }

  public void setSourceName(String sourceName) {
    this.sourceName = sourceName;
  }

  public MinimalSourceDetailsDTO sourceTypeCatalogVersion(String sourceTypeCatalogVersion) {
    this.sourceTypeCatalogVersion = sourceTypeCatalogVersion;
    return this;
  }

   /**
   * Get sourceTypeCatalogVersion
   * @return sourceTypeCatalogVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceTypeCatalogVersion() {
    return sourceTypeCatalogVersion;
  }

  public void setSourceTypeCatalogVersion(String sourceTypeCatalogVersion) {
    this.sourceTypeCatalogVersion = sourceTypeCatalogVersion;
  }

  public MinimalSourceDetailsDTO sourceTypeId(Long sourceTypeId) {
    this.sourceTypeId = sourceTypeId;
    return this;
  }

   /**
   * Get sourceTypeId
   * @return sourceTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSourceTypeId() {
    return sourceTypeId;
  }

  public void setSourceTypeId(Long sourceTypeId) {
    this.sourceTypeId = sourceTypeId;
  }

  public MinimalSourceDetailsDTO sourceTypeModel(String sourceTypeModel) {
    this.sourceTypeModel = sourceTypeModel;
    return this;
  }

   /**
   * Get sourceTypeModel
   * @return sourceTypeModel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceTypeModel() {
    return sourceTypeModel;
  }

  public void setSourceTypeModel(String sourceTypeModel) {
    this.sourceTypeModel = sourceTypeModel;
  }

  public MinimalSourceDetailsDTO sourceTypeProducer(String sourceTypeProducer) {
    this.sourceTypeProducer = sourceTypeProducer;
    return this;
  }

   /**
   * Get sourceTypeProducer
   * @return sourceTypeProducer
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceTypeProducer() {
    return sourceTypeProducer;
  }

  public void setSourceTypeProducer(String sourceTypeProducer) {
    this.sourceTypeProducer = sourceTypeProducer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MinimalSourceDetailsDTO minimalSourceDetailsDTO = (MinimalSourceDetailsDTO) o;
    return Objects.equals(this.assigned, minimalSourceDetailsDTO.assigned) &&
        Objects.equals(this.attributes, minimalSourceDetailsDTO.attributes) &&
        Objects.equals(this.expectedSourceName, minimalSourceDetailsDTO.expectedSourceName) &&
        Objects.equals(this.id, minimalSourceDetailsDTO.id) &&
        Objects.equals(this.sourceId, minimalSourceDetailsDTO.sourceId) &&
        Objects.equals(this.sourceName, minimalSourceDetailsDTO.sourceName) &&
        Objects.equals(this.sourceTypeCatalogVersion, minimalSourceDetailsDTO.sourceTypeCatalogVersion) &&
        Objects.equals(this.sourceTypeId, minimalSourceDetailsDTO.sourceTypeId) &&
        Objects.equals(this.sourceTypeModel, minimalSourceDetailsDTO.sourceTypeModel) &&
        Objects.equals(this.sourceTypeProducer, minimalSourceDetailsDTO.sourceTypeProducer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assigned, attributes, expectedSourceName, id, sourceId, sourceName, sourceTypeCatalogVersion, sourceTypeId, sourceTypeModel, sourceTypeProducer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MinimalSourceDetailsDTO {\n");
    
    sb.append("    assigned: ").append(toIndentedString(assigned)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    expectedSourceName: ").append(toIndentedString(expectedSourceName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    sourceName: ").append(toIndentedString(sourceName)).append("\n");
    sb.append("    sourceTypeCatalogVersion: ").append(toIndentedString(sourceTypeCatalogVersion)).append("\n");
    sb.append("    sourceTypeId: ").append(toIndentedString(sourceTypeId)).append("\n");
    sb.append("    sourceTypeModel: ").append(toIndentedString(sourceTypeModel)).append("\n");
    sb.append("    sourceTypeProducer: ").append(toIndentedString(sourceTypeProducer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

