/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
import org.radarcns.management.client.model.AttributeMapDTO;
import org.radarcns.management.client.model.SourceTypeDTO;

/**
 * ProjectDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T13:18:11.102+01:00")
public class ProjectDTO {
  @SerializedName("attributes")
  private List<AttributeMapDTO> attributes = new ArrayList<AttributeMapDTO>();

  @SerializedName("description")
  private String description = null;

  @SerializedName("endDate")
  private DateTime endDate = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("organization")
  private String organization = null;

  @SerializedName("projectAdmin")
  private Long projectAdmin = null;

  @SerializedName("projectName")
  private String projectName = null;

  /**
   * Gets or Sets projectStatus
   */
  public enum ProjectStatusEnum {
    @SerializedName("PLANNING")
    PLANNING("PLANNING"),
    
    @SerializedName("ONGOING")
    ONGOING("ONGOING"),
    
    @SerializedName("ENDED")
    ENDED("ENDED");

    private String value;

    ProjectStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("projectStatus")
  private ProjectStatusEnum projectStatus = null;

  @SerializedName("sourceTypes")
  private List<SourceTypeDTO> sourceTypes = new ArrayList<SourceTypeDTO>();

  @SerializedName("startDate")
  private DateTime startDate = null;

  public ProjectDTO attributes(List<AttributeMapDTO> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ProjectDTO addAttributesItem(AttributeMapDTO attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AttributeMapDTO> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AttributeMapDTO> attributes) {
    this.attributes = attributes;
  }

  public ProjectDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ProjectDTO endDate(DateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(DateTime endDate) {
    this.endDate = endDate;
  }

  public ProjectDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProjectDTO location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public ProjectDTO organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public ProjectDTO projectAdmin(Long projectAdmin) {
    this.projectAdmin = projectAdmin;
    return this;
  }

   /**
   * Get projectAdmin
   * @return projectAdmin
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getProjectAdmin() {
    return projectAdmin;
  }

  public void setProjectAdmin(Long projectAdmin) {
    this.projectAdmin = projectAdmin;
  }

  public ProjectDTO projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Get projectName
   * @return projectName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public ProjectDTO projectStatus(ProjectStatusEnum projectStatus) {
    this.projectStatus = projectStatus;
    return this;
  }

   /**
   * Get projectStatus
   * @return projectStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public ProjectStatusEnum getProjectStatus() {
    return projectStatus;
  }

  public void setProjectStatus(ProjectStatusEnum projectStatus) {
    this.projectStatus = projectStatus;
  }

  public ProjectDTO sourceTypes(List<SourceTypeDTO> sourceTypes) {
    this.sourceTypes = sourceTypes;
    return this;
  }

  public ProjectDTO addSourceTypesItem(SourceTypeDTO sourceTypesItem) {
    this.sourceTypes.add(sourceTypesItem);
    return this;
  }

   /**
   * Get sourceTypes
   * @return sourceTypes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<SourceTypeDTO> getSourceTypes() {
    return sourceTypes;
  }

  public void setSourceTypes(List<SourceTypeDTO> sourceTypes) {
    this.sourceTypes = sourceTypes;
  }

  public ProjectDTO startDate(DateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(DateTime startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectDTO projectDTO = (ProjectDTO) o;
    return Objects.equals(this.attributes, projectDTO.attributes) &&
        Objects.equals(this.description, projectDTO.description) &&
        Objects.equals(this.endDate, projectDTO.endDate) &&
        Objects.equals(this.id, projectDTO.id) &&
        Objects.equals(this.location, projectDTO.location) &&
        Objects.equals(this.organization, projectDTO.organization) &&
        Objects.equals(this.projectAdmin, projectDTO.projectAdmin) &&
        Objects.equals(this.projectName, projectDTO.projectName) &&
        Objects.equals(this.projectStatus, projectDTO.projectStatus) &&
        Objects.equals(this.sourceTypes, projectDTO.sourceTypes) &&
        Objects.equals(this.startDate, projectDTO.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, description, endDate, id, location, organization, projectAdmin, projectName, projectStatus, sourceTypes, startDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectDTO {\n");
    
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    projectAdmin: ").append(toIndentedString(projectAdmin)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    projectStatus: ").append(toIndentedString(projectStatus)).append("\n");
    sb.append("    sourceTypes: ").append(toIndentedString(sourceTypes)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

