/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.radarcns.management.client.model.MinimalProjectDetailsDTO;
import org.radarcns.management.client.model.SourceTypeDTO;

/**
 * SourceDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T13:18:11.102+01:00")
public class SourceDTO {
  @SerializedName("assigned")
  private Boolean assigned = null;

  @SerializedName("attributes")
  private Map<String, String> attributes = new HashMap<String, String>();

  @SerializedName("expectedSourceName")
  private String expectedSourceName = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("project")
  private MinimalProjectDetailsDTO project = null;

  @SerializedName("sourceId")
  private String sourceId = null;

  @SerializedName("sourceName")
  private String sourceName = null;

  @SerializedName("sourceType")
  private SourceTypeDTO sourceType = null;

  public SourceDTO assigned(Boolean assigned) {
    this.assigned = assigned;
    return this;
  }

   /**
   * Get assigned
   * @return assigned
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getAssigned() {
    return assigned;
  }

  public void setAssigned(Boolean assigned) {
    this.assigned = assigned;
  }

  public SourceDTO attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public SourceDTO putAttributesItem(String key, String attributesItem) {
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public SourceDTO expectedSourceName(String expectedSourceName) {
    this.expectedSourceName = expectedSourceName;
    return this;
  }

   /**
   * Get expectedSourceName
   * @return expectedSourceName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExpectedSourceName() {
    return expectedSourceName;
  }

  public void setExpectedSourceName(String expectedSourceName) {
    this.expectedSourceName = expectedSourceName;
  }

  public SourceDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SourceDTO project(MinimalProjectDetailsDTO project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(example = "null", value = "")
  public MinimalProjectDetailsDTO getProject() {
    return project;
  }

  public void setProject(MinimalProjectDetailsDTO project) {
    this.project = project;
  }

  public SourceDTO sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public SourceDTO sourceName(String sourceName) {
    this.sourceName = sourceName;
    return this;
  }

   /**
   * Get sourceName
   * @return sourceName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSourceName() {
    return sourceName;
  }

  public void setSourceName(String sourceName) {
    this.sourceName = sourceName;
  }

  public SourceDTO sourceType(SourceTypeDTO sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public SourceTypeDTO getSourceType() {
    return sourceType;
  }

  public void setSourceType(SourceTypeDTO sourceType) {
    this.sourceType = sourceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceDTO sourceDTO = (SourceDTO) o;
    return Objects.equals(this.assigned, sourceDTO.assigned) &&
        Objects.equals(this.attributes, sourceDTO.attributes) &&
        Objects.equals(this.expectedSourceName, sourceDTO.expectedSourceName) &&
        Objects.equals(this.id, sourceDTO.id) &&
        Objects.equals(this.project, sourceDTO.project) &&
        Objects.equals(this.sourceId, sourceDTO.sourceId) &&
        Objects.equals(this.sourceName, sourceDTO.sourceName) &&
        Objects.equals(this.sourceType, sourceDTO.sourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assigned, attributes, expectedSourceName, id, project, sourceId, sourceName, sourceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceDTO {\n");
    
    sb.append("    assigned: ").append(toIndentedString(assigned)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    expectedSourceName: ").append(toIndentedString(expectedSourceName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    sourceName: ").append(toIndentedString(sourceName)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

