/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.joda.time.DateTime;
import org.radarcns.management.client.model.MinimalSourceDetailsDTO;
import org.radarcns.management.client.model.ProjectDTO;

/**
 * SubjectDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-01T13:18:11.102+01:00")
public class SubjectDTO {
  @SerializedName("attributes")
  private Map<String, String> attributes = new HashMap<String, String>();

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("createdDate")
  private DateTime createdDate = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("externalLink")
  private String externalLink = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("lastModifiedBy")
  private String lastModifiedBy = null;

  @SerializedName("lastModifiedDate")
  private DateTime lastModifiedDate = null;

  @SerializedName("login")
  private String login = null;

  @SerializedName("project")
  private ProjectDTO project = null;

  @SerializedName("sources")
  private List<MinimalSourceDetailsDTO> sources = new ArrayList<MinimalSourceDetailsDTO>();

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("DEACTIVATED")
    DEACTIVATED("DEACTIVATED"),
    
    @SerializedName("ACTIVATED")
    ACTIVATED("ACTIVATED"),
    
    @SerializedName("DISCONTINUED")
    DISCONTINUED("DISCONTINUED"),
    
    @SerializedName("INVALID")
    INVALID("INVALID");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  public SubjectDTO attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public SubjectDTO putAttributesItem(String key, String attributesItem) {
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public SubjectDTO createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SubjectDTO createdDate(DateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(DateTime createdDate) {
    this.createdDate = createdDate;
  }

  public SubjectDTO externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public SubjectDTO externalLink(String externalLink) {
    this.externalLink = externalLink;
    return this;
  }

   /**
   * Get externalLink
   * @return externalLink
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExternalLink() {
    return externalLink;
  }

  public void setExternalLink(String externalLink) {
    this.externalLink = externalLink;
  }

  public SubjectDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SubjectDTO lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SubjectDTO lastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(DateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public SubjectDTO login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public SubjectDTO project(ProjectDTO project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(example = "null", value = "")
  public ProjectDTO getProject() {
    return project;
  }

  public void setProject(ProjectDTO project) {
    this.project = project;
  }

  public SubjectDTO sources(List<MinimalSourceDetailsDTO> sources) {
    this.sources = sources;
    return this;
  }

  public SubjectDTO addSourcesItem(MinimalSourceDetailsDTO sourcesItem) {
    this.sources.add(sourcesItem);
    return this;
  }

   /**
   * Get sources
   * @return sources
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<MinimalSourceDetailsDTO> getSources() {
    return sources;
  }

  public void setSources(List<MinimalSourceDetailsDTO> sources) {
    this.sources = sources;
  }

  public SubjectDTO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectDTO subjectDTO = (SubjectDTO) o;
    return Objects.equals(this.attributes, subjectDTO.attributes) &&
        Objects.equals(this.createdBy, subjectDTO.createdBy) &&
        Objects.equals(this.createdDate, subjectDTO.createdDate) &&
        Objects.equals(this.externalId, subjectDTO.externalId) &&
        Objects.equals(this.externalLink, subjectDTO.externalLink) &&
        Objects.equals(this.id, subjectDTO.id) &&
        Objects.equals(this.lastModifiedBy, subjectDTO.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDate, subjectDTO.lastModifiedDate) &&
        Objects.equals(this.login, subjectDTO.login) &&
        Objects.equals(this.project, subjectDTO.project) &&
        Objects.equals(this.sources, subjectDTO.sources) &&
        Objects.equals(this.status, subjectDTO.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, createdBy, createdDate, externalId, externalLink, id, lastModifiedBy, lastModifiedDate, login, project, sources, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectDTO {\n");
    
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    externalLink: ").append(toIndentedString(externalLink)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

