cacheFolder: ./.yarn/cache

enableImmutableInstalls: false

nodeLinker: node-modules


npmScopes:
  "uom-digital-health-software":
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN}"


yarnPath: .yarn/releases/yarn-3.6.4.cjs
