version: '3.7'
services:

    ## MP

    managementportal-app:
        image: ghcr.io/radar-base/managementportal/management-portal:dev
        environment:
            - SPRING_PROFILES_ACTIVE=prod,api-docs
            - SPRING_DATASOURCE_URL=jdbc:postgresql://managementportal-postgresql:5432/managementportal
            - SPRING_DATASOURCE_USERNAME=radarbase
            - SPRING_DATASOURCE_PASSWORD=radarbase
            - MANAGEMENTPORTAL_COMMON_ADMINPASSWORD=admin
            - MANAGEMENTPORTAL_FRONTEND_CLIENT_SECRET=secret
            - MANAGEMENTPORTAL_IDENTITYSERVER_INTERNAL=false # IF using external identity like ORY Kratos
            - MANAGEMENTPORTAL_IDENTITYSERVER_ADMINEMAIL=admin-email-here@radar-base.net
            - MANAGEMENTPORTAL_IDENTITYSERVER_SERVERURL=http://kratos:4433
            - MANAGEMENTPORTAL_IDENTITYSERVER_LOGINURL=http://localhost:3000
            - MANAGEMENTPORTAL_IDENTITYSERVER_SERVERADMINURL=http://kratos:4434
            - MANAGEMENTPORTAL_AUTHSERVER_INTERNAL=false # IF using external auth server like ORY Hydra
            - MANAGEMENTPORTAL_AUTHSERVER_SERVERURL=http://hydra:4444
            - MANAGEMENTPORTAL_AUTHSERVER_LOGINURL=http://localhost:4444
            - MANAGEMENTPORTAL_AUTHSERVER_SERVERADMINURL=http://hydra:4445
            - MANAGEMENTPORTAL_OAUTH_CLIENTS_FILE=/mp-includes/config/oauth_client_details.csv
            - MANAGEMENTPORTAL_CATALOGUESERVER_SERVERURL=http://catalogue-server:8080
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - JAVA_OPTS=-Xmx512m  # maximum heap size for the JVM running ManagementPortal, increase this as necessary
        ports:
            - "8080:8080"
        networks:
            - all-net
            - mp-net
            - default
        volumes:
            - ./etc:/mp-includes


    managementportal-postgresql:
        extends:
            file: postgresql.yml
            service: managementportal-postgresql
        networks:
            - mp-net

networks:
    all-net:
    mp-net:
    kratos-net:
