version: '3.8'

services:
    kratos-selfservice-ui-node:
        image:
            oryd/kratos-selfservice-ui-node
        environment:
            - LOG_LEAK_SENSITIVE_VALUES=true
            - KRATOS_PUBLIC_URL=http://kratos:4433
            - KRATOS_ADMIN_URL=http://kratos:4434
            - SECURITY_MODE=standalone
            - KRATOS_BROWSER_URL=http://127.0.0.1:4433
            - COOKIE_SECRET=unsafe_cookie_secret
            - CSRF_COOKIE_NAME=radar
            - CSRF_COOKIE_SECRET=unsafe_csrf_cookie_secret
        ports:
            - "3000:3000"
        volumes:
            - /tmp/ui-node/logs:/root/.npm/_logs

    kratos:
      depends_on:
        - kratos-migrate
      image: oryd/kratos:v1.0.0
      ports:
        - "4433:4433" # public
        - "4434:4434" # admin, should be closed in production
      restart: unless-stopped
      environment:
        - DSN=postgres://kratos:secret@postgresd-kratos/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
      volumes:
        - type: bind
          source: ./etc/config/kratos
          target: /etc/config/kratos

    kratos-migrate:
        image:
            oryd/kratos:v1.0.0
        environment:
            - DSN=postgres://kratos:secret@postgresd-kratos/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
        volumes:
            - type: bind
              source: ./etc/config/kratos
              target: /etc/config/kratos
        command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
        restart: on-failure

    postgresd-kratos:
        image: postgres:11.8
        environment:
            - POSTGRES_USER=kratos
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=kratos

    mailslurper:
        image: oryd/mailslurper:latest-smtps
        ports:
            - "4436:4436"
            - "4437:4437"
