version: '2'
services:
  smtp:
    image: namshi/smtp:latest
    networks:
      - mail
    volumes:
      - /var/spool/exim
    restart: always
    env_file:
      - ./etc/smtp.env # generate by filling in ./etc/smpt.env.template
