/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.api;

import org.radarcns.management.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthorityResourceApi
 */
@Ignore
public class AuthorityResourceApiTest {

    private final AuthorityResourceApi api = new AuthorityResourceApi();

    
    /**
     * getAllAuthorities
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAuthoritiesUsingGETTest() throws ApiException {
        List<String> response = api.getAllAuthoritiesUsingGET();

        // TODO: test validations
    }
    
}
