/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.api;

import org.radarcns.management.client.ApiException;
import org.radarcns.management.client.model.ClientDetailsDTO;
import org.radarcns.management.client.model.ClientPairInfoDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OAuthClientsResourceApi
 */
@Ignore
public class OAuthClientsResourceApiTest {

    private final OAuthClientsResourceApi api = new OAuthClientsResourceApi();

    
    /**
     * createOAuthClient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOAuthClientUsingPOSTTest() throws ApiException {
        ClientDetailsDTO clientDetailsDTO = null;
        ClientDetailsDTO response = api.createOAuthClientUsingPOST(clientDetailsDTO);

        // TODO: test validations
    }
    
    /**
     * deleteOAuthClient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOAuthClientUsingDELETETest() throws ApiException {
        String id = null;
        api.deleteOAuthClientUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * getOAuthClientById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOAuthClientByIdUsingGETTest() throws ApiException {
        String id = null;
        ClientDetailsDTO response = api.getOAuthClientByIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * getOAuthClients
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOAuthClientsUsingGETTest() throws ApiException {
        List<ClientDetailsDTO> response = api.getOAuthClientsUsingGET();

        // TODO: test validations
    }
    
    /**
     * getRefreshToken
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRefreshTokenUsingGETTest() throws ApiException {
        String login = null;
        String clientId = null;
        ClientPairInfoDTO response = api.getRefreshTokenUsingGET(login, clientId);

        // TODO: test validations
    }
    
    /**
     * updateOAuthClient
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateOAuthClientUsingPUTTest() throws ApiException {
        ClientDetailsDTO clientDetailsDTO = null;
        ClientDetailsDTO response = api.updateOAuthClientUsingPUT(clientDetailsDTO);

        // TODO: test validations
    }
    
}
