/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.api;

import org.radarcns.management.client.ApiException;
import org.radarcns.management.client.model.RoleDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RoleResourceApi
 */
@Ignore
public class RoleResourceApiTest {

    private final RoleResourceApi api = new RoleResourceApi();

    
    /**
     * createRole
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRoleUsingPOSTTest() throws ApiException {
        RoleDTO roleDTO = null;
        RoleDTO response = api.createRoleUsingPOST(roleDTO);

        // TODO: test validations
    }
    
    /**
     * getAllAdminRoles
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAdminRolesUsingGETTest() throws ApiException {
        List<RoleDTO> response = api.getAllAdminRolesUsingGET();

        // TODO: test validations
    }
    
    /**
     * getAllRoles
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllRolesUsingGETTest() throws ApiException {
        List<RoleDTO> response = api.getAllRolesUsingGET();

        // TODO: test validations
    }
    
    /**
     * getRole
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRoleUsingGETTest() throws ApiException {
        String projectName = null;
        String authorityName = null;
        RoleDTO response = api.getRoleUsingGET(projectName, authorityName);

        // TODO: test validations
    }
    
    /**
     * updateRole
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRoleUsingPUTTest() throws ApiException {
        RoleDTO roleDTO = null;
        RoleDTO response = api.updateRoleUsingPUT(roleDTO);

        // TODO: test validations
    }
    
}
