/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.api;

import org.radarcns.management.client.ApiException;
import org.radarcns.management.client.model.SourceDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SourceResourceApi
 */
@Ignore
public class SourceResourceApiTest {

    private final SourceResourceApi api = new SourceResourceApi();

    
    /**
     * createSource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSourceUsingPOSTTest() throws ApiException {
        SourceDTO sourceDTO = null;
        SourceDTO response = api.createSourceUsingPOST(sourceDTO);

        // TODO: test validations
    }
    
    /**
     * deleteSource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSourceUsingDELETETest() throws ApiException {
        String sourceName = null;
        api.deleteSourceUsingDELETE(sourceName);

        // TODO: test validations
    }
    
    /**
     * getAllSources
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSourcesUsingGETTest() throws ApiException {
        List<SourceDTO> response = api.getAllSourcesUsingGET();

        // TODO: test validations
    }
    
    /**
     * getSource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSourceUsingGETTest() throws ApiException {
        String sourceName = null;
        SourceDTO response = api.getSourceUsingGET(sourceName);

        // TODO: test validations
    }
    
    /**
     * updateSource
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSourceUsingPUTTest() throws ApiException {
        SourceDTO sourceDTO = null;
        SourceDTO response = api.updateSourceUsingPUT(sourceDTO);

        // TODO: test validations
    }
    
}
