/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.api;

import org.radarcns.management.client.ApiException;
import org.radarcns.management.client.model.SourceDataDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SourceDataResourceApi
 */
@Ignore
public class SourceDataResourceApiTest {

    private final SourceDataResourceApi api = new SourceDataResourceApi();

    
    /**
     * createSourceData
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSourceDataUsingPOSTTest() throws ApiException {
        SourceDataDTO sourceDataDTO = null;
        SourceDataDTO response = api.createSourceDataUsingPOST(sourceDataDTO);

        // TODO: test validations
    }
    
    /**
     * deleteSourceData
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSourceDataUsingDELETETest() throws ApiException {
        String sourceDataName = null;
        api.deleteSourceDataUsingDELETE(sourceDataName);

        // TODO: test validations
    }
    
    /**
     * getAllSourceData
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSourceDataUsingGETTest() throws ApiException {
        List<SourceDataDTO> response = api.getAllSourceDataUsingGET();

        // TODO: test validations
    }
    
    /**
     * getSourceData
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSourceDataUsingGETTest() throws ApiException {
        String sourceDataName = null;
        SourceDataDTO response = api.getSourceDataUsingGET(sourceDataName);

        // TODO: test validations
    }
    
    /**
     * updateSourceData
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSourceDataUsingPUTTest() throws ApiException {
        SourceDataDTO sourceDataDTO = null;
        SourceDataDTO response = api.updateSourceDataUsingPUT(sourceDataDTO);

        // TODO: test validations
    }
    
}
