/*
 * ManagementPortal API
 * ManagementPortal API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.radarcns.management.client.api;

import org.radarcns.management.client.ApiException;
import org.radarcns.management.client.model.ManagedUserVM;
import org.radarcns.management.client.model.ProjectDTO;
import org.radarcns.management.client.model.ResponseEntity;
import org.radarcns.management.client.model.UserDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserResourceApi
 */
@Ignore
public class UserResourceApiTest {

    private final UserResourceApi api = new UserResourceApi();

    
    /**
     * createUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserUsingPOSTTest() throws ApiException {
        ManagedUserVM managedUserVM = null;
        ResponseEntity response = api.createUserUsingPOST(managedUserVM);

        // TODO: test validations
    }
    
    /**
     * deleteUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserUsingDELETETest() throws ApiException {
        String login = null;
        api.deleteUserUsingDELETE(login);

        // TODO: test validations
    }
    
    /**
     * getAllUsers
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUsersUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        String projectName = null;
        String authority = null;
        List<String> sort = null;
        List<UserDTO> response = api.getAllUsersUsingGET(page, size, projectName, authority, sort);

        // TODO: test validations
    }
    
    /**
     * getUserProjects
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserProjectsUsingGETTest() throws ApiException {
        String login = null;
        List<ProjectDTO> response = api.getUserProjectsUsingGET(login);

        // TODO: test validations
    }
    
    /**
     * getUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserUsingGETTest() throws ApiException {
        String login = null;
        UserDTO response = api.getUserUsingGET(login);

        // TODO: test validations
    }
    
    /**
     * updateUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserUsingPUTTest() throws ApiException {
        ManagedUserVM managedUserVM = null;
        UserDTO response = api.updateUserUsingPUT(managedUserVM);

        // TODO: test validations
    }
    
}
