@Suppress("ConstPropertyName")
object Versions {

    const val assertj = "3.23.1"
    const val jhipsterServer = "8.2.0"
    const val hazelcast = "5.2.5"
    const val hazelcastHibernate = "5.1.0"
    const val hikaricp = "5.0.1"
    const val liquibaseSlf4j = "4.1.0"
    const val liquibase = "4.22.0"
    const val postgresql = "42.6.1"
    const val springdoc = "1.6.15"
    const val springBoot = "3.1.9"
    const val springFramework = "5.3.27"
    const val springDependencyManagement = "1.1.3"
    const val springData = "2021.2.5"
    const val thymeleaf = "3.1.2.RELEASE"
    const val springSession = "2021.2.0"
    const val gatling = "3.8.4"
    const val mapstruct = "1.5.5.Final"
    const val jackson = "2.16.1"
    const val javaxXmlBind = "2.3.3"
    const val javaxJaxbCore = "2.3.0.1"
    const val javaxJaxbRuntime = "2.3.8"
    const val javaxActivation = "1.1.1"
    const val mockito = "4.8.1"
    const val mockitoKotlin = "5.1.0"
    const val slf4j = "2.0.7"
    const val logback = "1.4.11"
    const val oauthJwt = "4.4.0"
    const val junit = "5.10.0"
    const val okhttp = "4.10.0"
    const val hsqldb = "2.7.2"
    const val coroutines = "1.8.0"
    const val ktor = "2.3.9"
    const val radarCommons = "1.0.0"
    const val hamcrest = "2.2"
    const val wiremock = "3.0.1"
    const val kotlin = "1.9.10"
    const val micrometer = "1.12.3"
    const val hibernateOrm = "6.4.4.Final"
    const val hibernateValidator = "8.0.0.Final"
    const val findbugAnnotation = "3.0.2"
    const val dokka = "1.8.20"
    const val undercouch = "5.6.0"


    const val wrapper = "8.4"
}
