package org.radarcns.management.service;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.radarcns.management.ManagementPortalTestApp;
import org.radarcns.management.domain.MetaToken;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.transaction.annotation.Transactional;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = ManagementPortalTestApp.class)
@Transactional
public class MetaTokenServiceTest {


    @Autowired
    private MetaTokenService metaTokenService;

    @Test
    public void testSaveMetaToken() {
        MetaToken token = new MetaToken();
        token.setFetched(false);
        token.setToken("{\"access_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInNvdXJjZXMiOltdLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiTWFuYWdlbWVudFBvcnRhbCIsImF1dGhvcml0aWVzIjpbIlJPTEVfU1lTX0FETUlOIl0sImNsaWVudF9pZCI6Ik1hbmFnZW1lbnRQb3J0YWxhcHAiLCJhdWQiOiJyZXNfTWFuYWdlbWVudFBvcnRhbCIsImdyYW50X3R5cGUiOiJwYXNzd29yZCIsInNjb3BlIjpbIlNPVVJDRVRZUEUuQ1JFQVRFIiwiU09VUkNFVFlQRS5SRUFEIiwiU09VUkNFVFlQRS5VUERBVEUiLCJTT1VSQ0VUWVBFLkRFTEVURSIsIlNPVVJDRURBVEEuQ1JFQVRFIiwiU09VUkNFREFUQS5SRUFEIiwiU09VUkNFREFUQS5VUERBVEUiLCJTT1VSQ0VEQVRBLkRFTEVURSIsIlNPVVJDRS5DUkVBVEUiLCJTT1VSQ0UuUkVBRCIsIlNPVVJDRS5VUERBVEUiLCJTT1VSQ0UuREVMRVRFIiwiU1VCSkVDVC5DUkVBVEUiLCJTVUJKRUNULlJFQUQiLCJTVUJKRUNULlVQREFURSIsIlNVQkpFQ1QuREVMRVRFIiwiVVNFUi5DUkVBVEUiLCJVU0VSLlJFQUQiLCJVU0VSLlVQREFURSIsIlVTRVIuREVMRVRFIiwiUk9MRS5DUkVBVEUiLCJST0xFLlJFQUQiLCJST0xFLlVQREFURSIsIlJPTEUuREVMRVRFIiwiUFJPSkVDVC5DUkVBVEUiLCJQUk9KRUNULlJFQUQiLCJQUk9KRUNULlVQREFURSIsIlBST0pFQ1QuREVMRVRFIiwiT0FVVEhDTElFTlRTLkNSRUFURSIsIk9BVVRIQ0xJRU5UUy5SRUFEIiwiT0FVVEhDTElFTlRTLlVQREFURSIsIk9BVVRIQ0xJRU5UUy5ERUxFVEUiLCJBVURJVC5DUkVBVEUiLCJBVURJVC5SRUFEIiwiQVVESVQuVVBEQVRFIiwiQVVESVQuREVMRVRFIiwiQVVUSE9SSVRZLkNSRUFURSIsIkFVVEhPUklUWS5SRUFEIiwiQVVUSE9SSVRZLlVQREFURSIsIkFVVEhPUklUWS5ERUxFVEUiLCJNRUFTVVJFTUVOVC5DUkVBVEUiLCJNRUFTVVJFTUVOVC5SRUFEIiwiTUVBU1VSRU1FTlQuVVBEQVRFIiwiTUVBU1VSRU1FTlQuREVMRVRFIl0sImV4cCI6MTUzMjQ1MjMyOCwiaWF0IjoxNTMyNDM3OTI4LCJqdGkiOiJkY2E3MDQ3Yi00NjdlLTQ5OTEtOWY1Zi03N2NiMTA4MTA0YzQifQ.MEUCIGHhvq-C9WRHAYecpgd3SM6ih2ejqwJ3Lp_qwsVd8o-mAiEAswpsnOoTi3qQC49y5hCFK3QODKt_9pJglFDxwPqnG0A\",\"token_type\":\"bearer\",\"expires_in\":14399,\"scope\":\"SOURCETYPE.CREATE SOURCETYPE.READ SOURCETYPE.UPDATE SOURCETYPE.DELETE SOURCEDATA.CREATE SOURCEDATA.READ SOURCEDATA.UPDATE SOURCEDATA.DELETE SOURCE.CREATE SOURCE.READ SOURCE.UPDATE SOURCE.DELETE SUBJECT.CREATE SUBJECT.READ SUBJECT.UPDATE SUBJECT.DELETE USER.CREATE USER.READ USER.UPDATE USER.DELETE ROLE.CREATE ROLE.READ ROLE.UPDATE ROLE.DELETE PROJECT.CREATE PROJECT.READ PROJECT.UPDATE PROJECT.DELETE OAUTHCLIENTS.CREATE OAUTHCLIENTS.READ OAUTHCLIENTS.UPDATE OAUTHCLIENTS.DELETE AUDIT.CREATE AUDIT.READ AUDIT.UPDATE AUDIT.DELETE AUTHORITY.CREATE AUTHORITY.READ AUTHORITY.UPDATE AUTHORITY.DELETE MEASUREMENT.CREATE MEASUREMENT.READ MEASUREMENT.UPDATE MEASUREMENT.DELETE\",\"sub\":\"admin\",\"sources\":[],\"grant_type\":\"password\",\"roles\":[],\"iss\":\"ManagementPortal\",\"iat\":1532437928,\"jti\":\"dca7047b-467e-4991-9f5f-77cb108104c4\"}");
        MetaToken saved = metaTokenService.save(token);
        assertNotNull(saved.getId());
        assertNotNull(saved.getTokenName());

    }
}
